[package]
name = "day2"
version = "0.1.0"
authors = ["Joseph Bauer <root@thesudorm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.0.0-beta.3"
